---
language: csharp
solution: pusher-dotnet-server.sln
script:
  - xbuild /p:Configuration=Release pusher-dotnet-server.sln
  - mono .\packages\NUnit.Console.3.0.1\tools\nunit3-console.exe .\PusherServer.Tests\bin\Release\PusherServer.Tests.dll
