name: Build

on:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup MS Build
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Restore dependencies
      run: nuget restore pusher-dotnet-server.sln
    - name: Build
      run: msbuild /p:deterministic=true /p:msbuildArchitecture=x64 /p:configuration=Release pusher-dotnet-server.sln
    - name: Test
      env:
        PUSHER_APP_ID: ${{ secrets.CI_APP_ID }}
        PUSHER_APP_KEY: ${{ secrets.CI_APP_KEY }}
        PUSHER_APP_SECRET: ${{ secrets.CI_APP_SECRET }}
        PUSHER_APP_HOST: api-${{ secrets.CI_APP_CLUSTER }}.pusher.com
        PUSHER_APP_WEB_SOCKET_HOST: ws-${{ secrets.CI_APP_CLUSTER }}.pusher.com
      run: vstest.console.exe "./PusherServer.Tests/bin/Release/net45/PusherServer.Tests.dll" /TestAdapterPath:"./PusherServer.Tests/bin/Release/net45/"
    - name: Test pack
      run: msbuild /t:Pack /p:configuration=release PusherServer/PusherServer.csproj
