name: Github Release

on:
  push:
    tags:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare description
        run: |
          csplit -s CHANGELOG.md "/##/" {1}
          cat xx01 > CHANGELOG.tmp
      - name: Prepare tag
        run: |
          export REF=${{ github.ref }}
          export TAG=${REF##*/}
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body_path: CHANGELOG.tmp
          draft: false
          prerelease: false
